# this is basically the same as CAS_office.json (iirc) but it uses the vulkan renderer with some minor optimizations
[player]
dxvk = false
renderer = "Vulkan"
gpu = "prime-discrete"

[player.fflags]
DFIntTaskSchedulerTargetFps = 999
FFlagHandleAltEnterFullscreenManually= false
FFlagAnimationClipMemCacheEnabled = true
FFlagFixGraphicsQuality = true
FFlagCommitToGraphicsQualityFix = true
FFlagDontCreatePingJob = true
FFlagFastGPULightCulling3 = true
FFlagRenderGpuTextureCompressor = true
FFlagGraphicsCheckComputeSupport = true

DFIntCSGLevelOfDetailSwitchingDistance = 0
DFIntCSGLevelOfDetailSwitchingDistanceL12 = 0
DFIntCSGLevelOfDetailSwitchingDistanceL23 = 0
DFIntCSGLevelOfDetailSwitchingDistanceL34 = 0
FIntRenderShadowIntensity = 0
FIntDebugForceMSAASamples = 0
FIntRenderLocalLightUpdatesMax = 1
FIntRenderLocalLightUpdatesMin = 1
FFlagDisablePostFx = true
FFlagDebugDisableTelemetryEphemeralCounter = true
FFlagDebugDisableTelemetryEphemeralStat = true
FFlagDebugDisableTelemetryEventIngest = true
FFlagDebugDisableTelemetryPoint = true
FFlagDebugDisableTelemetryV2Counter = true
FFlagDebugDisableTelemetryV2Event = true
FFlagDebugDisableTelemetryV2Stat = true
DFFlagAudioDeviceTelemetry = false
DFFlagEnableHardwareTelemetry = false
